### ISSUE TITLE
Better convert options for ePub output

### ISSUE THREAD

**Issue by anthonynelzin** [honkit/honkit#107]
HonKit provides a wide array of convert options for the PDF output, but none for the ePub output. Worse, it hardcodes defaults values (cf. honkit/packages/honkit/src/output/ebook/getConvertOptions.js) that it probably shouldn't. As least, HonKit should add the following general settings:

- `book-producer`: currently set to "HonKit", should be user-configurable
- `publisher`: currently set to "HonKit", should absolutely be user-configurable

Some other missing or hardcoded values could be available as general settings or ePub specific options:

- `pubdate`: to set the publication date of the book
- `series` and `series-index`: to set the series the book belongs to, and the index of the book in this series
- `epub.toc.position`: to set the position of the ToC at the end of the book instead of the start (see --epub-toc-at-end in ebook-convert options)
- `epub.toc.title`: to set the title of the ToC, as in some languages, a ToC at the beginning of the book has a different name as a ToC at the end of the book (eg "Sommaire" and "Table des matières" in French)

This would go a long way in making the ePub output more robust (and, speaking as a publisher, more "store-ready").

- HonKit version: 3.5.5

**Comment by azu** [comment]
Make sense.

Currently, HonKit does not define `epub` specific options.

- [Configuration · HonKit Documentation](https://honkit.netlify.app/config.html)

It is good that we add epub specific option as `epub.*` options.

- <https://github.com/honkit/honkit/blob/master/packages/honkit/src/output/ebook/getConvertOptions.js>
- <https://manual.calibre-ebook.com/generated/en/ebook-convert.html>

**Comment by anthonynelzin** [comment]
Opened a PR for the first part of my issue. I will work on the missing values and the ePub-specific options tomorrow.
