### ISSUE TITLE
Next section button not working all the time

### ISSUE THREAD

**Issue by chris-rock** [honkit/honkit#109]
## Summary

Great work @azu! Thank you. I found a small issue regarding the user navigation. It seems that the forward/backward buttons are not working correctly when subsections are used

- HonKit version:

3.6.0

## Step to reproduce

1. Open https://honkit.netlify.app/syntax/markdown.html
2. Click next
<img width="99" alt="Screen Shot 2020-08-14 at 10 41 46" src="https://user-images.githubusercontent.com/1178413/90231004-c2fb8180-de1a-11ea-87e3-4ad8adc889b2.png">
3. you will not be able to reach the 'Paragraphs' section

## Expected results

The next section button switches the page to the next section

## Actual results

As soon as subsections are used, the forward/backward buttons do not work as expected.

<img width="248" alt="Screen Shot 2020-08-14 at 10 44 19" src="https://user-images.githubusercontent.com/1178413/90231218-1ec60a80-de1b-11ea-851b-bbf0355bc2ee.png">

**Comment by azu** [comment]
I confirm it.
This issue is only occured on https://honkit.netlify.app/syntax/markdown.html ?

**Comment by chris-rock** [comment]
I experienced it on my own docs book as well. I experienced it on subsections only, though. Maybe the anchor is also causing trouble.

**Comment by azu** [comment]
Thanks.

I've also confirmed this bug in the original GitBook.


- [Fix to ignore anchor points by mizunashi-mana · Pull Request #1467 · GitbookIO/gitbook](https://github.com/GitbookIO/gitbook/pull/1467)

We'll fix this bug.

**Comment by azu** [comment]
This issue will be fixed in [v3.6.1](https://github.com/honkit/honkit/releases/tag/v3.6.1)

@chris-rock Thanks for report!

**Comment by chris-rock** [comment]
Perfect, thank you @azu your fix works like a charm!
