### ISSUE TITLE
pdf export does not print the correct book title 

### ISSUE THREAD

**Issue by chris-rock** [honkit/honkit#115]
## Summary

I've build  the honkit documentation as pdf via `honkit pdf ./ ` and expected  to see the book title on top of  the page, but it displays an arbitrary section. For honkit the top-right corner displays `Content References`. I was expecting to see the book title there.

<img width="785" alt="Screen Shot 2020-08-21 at 09 18 10" src="https://user-images.githubusercontent.com/1178413/90863396-3ce9b880-e38f-11ea-88e3-90611da64276.png">

- HonKit version:

## Step to reproduce

1. `honkit pdf ./`
2. open book.pdf

## Expected results

displays book title in page header

## Actual results

displays a title of a subpage

**Comment by azu** [comment]
I'm not familiar with `ebook-convert` and ebook-convert's [--chapter](https://manual.calibre-ebook.com/generated/en/ebook-convert.html#cmdoption-ebook-convert-chapter) decide the chapter title?

The `--chapter` is hardcode in HonKit source code.

https://github.com/honkit/honkit/blob/fd7b05b6459885379962b00000bf6825bde3c1d2/packages/honkit/src/output/ebook/getConvertOptions.js#L35

I could not found how to hardcode the book title into the `--chapter` option.

If it is possible, we can support this as an option.

📝 Example, HonKit document

<img width="898" alt="image" src="https://user-images.githubusercontent.com/19714/90870391-798bd300-e3d4-11ea-937e-5c246d7649b6.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/19714/90870523-a93adb00-e3d4-11ea-9bf6-39fe43a4a1b3.png">

[book.pdf](https://github.com/honkit/honkit/files/5107730/book.pdf)

**Comment by chris-rock** [comment]
Strange that I get a different output for Honkit documentation, probably mac only.

**Comment by chris-rock** [comment]
Lets close it for now until we know the root cause

**Comment by azu** [comment]
Fmm, I've used macOS.
Maybe it related with ebook-convert version.

My env:

macOS 10.15.6

```
$ ebook-convert --version
ebook-convert (calibre 3.47.1)
```

**Comment by chris-rock** [comment]
I use macOS 10.15.6

```
$ ebook-convert --version
ebook-convert (calibre 4.23.0)
Created by: Kovid Goyal <kovid@kovidgoyal.net>
```
