### ISSUE TITLE
epub generation: fail for CSS image path mis-detecting?

### ISSUE THREAD

**Issue by tsuyoshicho** [honkit/honkit#130]
## Summary

Create PDF & EPUB, EPUB is success but PDF is failed.
PDF include CSS background image for ./images/*.png contain fail.
(Web Hosted also success see source's GitHub Pages)

- HonKit version:
3.6.6 at 2020/09/23

## Step to reproduce

1. checkout source
2. build to PDF

### Link to code example:

- source : https://github.com/tsuyoshicho/WhenScarletIceMelted
- result : https://github.com/tsuyoshicho/WhenScarletIceMelted/runs/1152526006?check_suite_focus=true#step:7:43

## Expected results

Create PDF with image success.

## Actual results

see result link

log attaching

- stdout log  : [pdf.log](https://github.com/honkit/honkit/files/5264935/pdf.log)
- stderr log  : [pdf_stderr.log](https://github.com/honkit/honkit/files/5264948/pdf_stderr.log)
- Generate CSS: [pdf-1600823806151.css.txt](https://github.com/honkit/honkit/files/5264951/pdf-1600823806151.css.txt)

```
$ tree /f C:\Users\<userid>\AppData\Local\Temp\tmp-1952MQvyf79s5qc7
Folder PATH listing for volume Windows
Volume serial number is 000001DA 0882:F2A0
C:\USERS\<userid>\APPDATA\LOCAL\TEMP\TMP-1952MQVYF79S5QC7
│   .editorconfig
│   .gitattributes
│   .gitignore
│   .textlintrc
│   6c50c8.png
│   ebook-1600823806054.css
│   GLOSSARY.html
│   index.html
│   LICENSE.html
│   oldplugin.txt
│   package-lock.json
│   package.json
│   pdf-1600823806151.css
│   SUMMARY.html
│   website-1600823805986.css
│
├───.github
│   │   renovate.json
│   │
│   └───workflows
│           deploy.yml
│           release.yml
│           reviewdog.yml
│
├───assets
│   └───images
│       └───uml
│               .gitkeep
│
├───doc
│       .textlintrc
│       chapter1-1.adoc
│       chapter1-1.html
│
├───gitbook
│   │   ebook.css
│   │   epub.css
│   │   mobi.css
│   │   pdf.css
│   │
│   └───gitbook-plugin-highlight
│           ebook.css
│           website.css
│
├───images
│       gm.png
│       oreshalarry2.png
│       reaper.png
│       reapermini.png
│       tako.png
│       takomini.png
│
└───styles
        ebook.scss
        pdf.scss
        website.scss
        _common.scss
        _commonh.scss
        _commonv.scss
        _replay.scss
        _replayh.scss
        _replayv.scss
        _speechballoonsh.scss
        _speechballoonsv.scss
```

**Comment by azu** [comment]
The log show following, but actual image path is `images/gm.png`.

>  Error: The file /tmp/tmp-3301781BME967PEq/gm.png was not found!

This error is caused by this mismatch. but We do not found the reason of mismatch...

- https://github.com/honkit/honkit/blob/ed8ec44549c4ed9253c56dc9f24fda1f34449953/packages/honkit/src/output/ebook/getPDFTemplate.ts

Maybe,  `honkit pdf` to use `ebook.css` instead of `pdf.css`
https://github.com/honkit/honkit/blob/f1512f4eef2db37d74442c6cf86cc0435a539b3f/packages/%40honkit/theme-default/package.json#L95
https://github.com/tsuyoshicho/WhenScarletIceMelted/blob/227ac889649b530008c09c787cd8ac4deb45c874/book.json#L23-L25

**Comment by tsuyoshicho** [comment]
Okay, I'm tring to ebook.css for PDF.

**Comment by tsuyoshicho** [comment]
https://github.com/tsuyoshicho/WhenScarletIceMelted/releases/tag/v1.0.2
Fix Good!

Thanks for your guesses and suggestions.

## workaround care
ebook.sass(css) rename to epub.sass(css)

## after care
ebook.css asset search rule unmatch.
exact case : pdf,epub(and mobi...) coud are correct at same css.

**Comment by azu** [comment]
`honkit pdf` flow:

- if has ebook.css 
  - use ebook.css
- else if has pdf.css
  - use pdf.css
- else 
  - default

**Comment by tsuyoshicho** [comment]
Close OK.
(But I think ebook.css guaranteed to work correct at PDF,EPUB,MOBI?)

**Comment by azu** [comment]
> ebook.css guaranteed to work correct at PDF,EPUB,MOBI?

It depended on CSS file, I think.

**Comment by tsuyoshicho** [comment]
Mnnn...、epub generate success/but pdf failed by my css.
Because, asset image resolve fail (epub flatten asset, pdf keep file tree)...This point is base css feature. it need work fine both/all type at common file layout. I think.

---

This rule to keep in mind.
no reproduce it.

**Comment by azu** [comment]
> Because, asset image resolve fail (epub flatten asset, pdf keep file tree)...

Ah, OK It looks like another issue.

Can you create a minimal reproduce repository? 

📝 [`resolveFile`](https://github.com/honkit/honkit/blob/ed8ec44549c4ed9253c56dc9f24fda1f34449953/packages/honkit/src/output/modifiers/resolveLinks.ts) help us to resolve file path in HTML, but does it works on CSS?

**Comment by azu** [comment]
I've tested your https://github.com/tsuyoshicho/WhenScarletIceMelted.
epub is flat dir.

It is an issue or limitation of epub, it is not pdf issue. (I'm not faimilar with epub spec)
<img width="265" alt="image" src="https://user-images.githubusercontent.com/19714/94927570-6dc81c00-04fd-11eb-8030-873713c97ec2.png">

Maybe, create another issue about epub's image path.

**Comment by azu** [comment]
📝 Its related to ebook-convert https://manual.calibre-ebook.com/generated/en/ebook-convert.html#epub-output-options

**Comment by tsuyoshicho** [comment]
Oh, Thanks for your re-open.

I understand it.
This issue relative at epub.

**Comment by tsuyoshicho** [comment]
(Currently, GLOSSARY.md use image. This is workaround for epub do not contain asset for css; I forgot it for old workaround :-<)

root cause: ebook-convert, HTML image and other resolve to flatten move and link fix, but CSS contents,background do not resolve (file move,rewrite link)

affect : When ebook.css(sass/scss/less) use to epub, css image asset and other, do not resolve path, need root in it.
workaround: epub css split to other(ex PDF) and use asset write to flat(e.g. background=img), then html(markdown/asciidoc) use to link (e.g. img src=/path/to/asset/img), this html convert and file flatten work correct.

**Comment by tsuyoshicho** [comment]
## research ebook-convert and epub rule

## version

in Windows 10 Pro 20H1

```
$ ebook-convert --version
ebook-convert.exe (calibre 5.1.0)
Created by: Kovid Goyal <kovid@kovidgoyal.net>
```

### epub
[Open Publication Structure \(OPS\) 2\.0\.1 v1\.0](http://idpf.org/epub/20/spec/OPS_2.0_latest.htm)


### ebook-convert
[E\-book conversion — calibre 5\.1\.0 documentation](https://manual.calibre-ebook.com/conversion.html#id7)

table
> Stages of the conversion pipeline

row `structure`

> Post structure detection, but before CSS flattening and font size conversion. Use to debug font size conversion and CSS transforms.

rel info
[ebook\-convert\(1\) — calibre — Debian unstable — Debian Manpages](https://manpages.debian.org/unstable/calibre/ebook-convert.1.ja.html)

### trial convert

1. generate epub in https://github.com/tsuyoshicho/WhenScarletIceMelted
2. epub file extract and apply patch below
3. move file (gm.png, oreshalarry2.png, reaper.png, reapermini.png, tako.png, takomini.png) from root to ./images/
4. re generate epub command above azn suggest in https://github.com/honkit/honkit/issues/130#issuecomment-702784473

This process success image and result epub contain flat html/css and move image to root.

patch in book/book_mod

```patch
diff -u book_mod\chapter1-1.html book\chapter1-1.html
--- book_mod\chapter1-1.html	Sat Oct 03 12:28:10 2020
+++ book\chapter1-1.html	Sat Oct 03 11:35:26 2020
@@ -37,7 +37,7 @@
 </div>
 <div class="sect">
 <div class="sect">
-<img src="images/tako.png" alt="知性化タコ 「メルクリウスの盗掘屋」" class="calibre14"/>
+<img src="tako.png" alt="知性化タコ 「メルクリウスの盗掘屋」" class="calibre14"/>
 </div>
 </div>
 <div class="sect">
@@ -57,7 +57,7 @@
 </div>
 <div class="sect">
 <div class="sect">
-<img src="images/reaper.png" alt="サプリメント「サンワード」のサンプルＰＣ 戦闘円盤" class="calibre14"/>
+<img src="reaper.png" alt="サプリメント「サンワード」のサンプルＰＣ 戦闘円盤" class="calibre14"/>
 </div>
 </div>
 <div class="sect">
@@ -701,7 +701,7 @@
 </div>
 <div class="sect">
 <div class="sect">
-<img src="images/oreshalarry2.png" alt="Larry氏画、加工清水三毛、2013年" class="calibre14"/>
+<img src="oreshalarry2.png" alt="Larry氏画、加工清水三毛、2013年" class="calibre14"/>
 </div>
 </div>
 <div class="sect">
diff -u book_mod\GLOSSARY.html book\GLOSSARY.html
--- book_mod\GLOSSARY.html	Sat Oct 03 12:28:29 2020
+++ book\GLOSSARY.html	Sat Oct 03 11:35:26 2020
@@ -20,11 +20,11 @@
 <hr class="pcalibre6 calibre22 pcalibre5"/>
 <p class="calibre8">CSSのcontent対策</p>
 <h1 id="gm" class="pcalibre1 calibre6 pcalibre">GM</h1>
-<p class="calibre8"><img src="images/gm.png" alt="GMアイコン" class="calibre14"/></p>
+<p class="calibre8"><img src="gm.png" alt="GMアイコン" class="calibre14"/></p>
 <h1 id="pc1-ハルノブ" class="pcalibre1 calibre6 pcalibre">PC1 ハルノブ</h1>
-<p class="calibre8"><img src="images/takomini.png" alt="ハルノブアイコン" class="calibre14"/></p>
+<p class="calibre8"><img src="takomini.png" alt="ハルノブアイコン" class="calibre14"/></p>
 <h1 id="pc2-オレーシャ" class="pcalibre1 calibre6 pcalibre">PC2 オレーシャ</h1>
-<p class="calibre8"><img src="images/reapermini.png" alt="オレーシャアイコン" class="calibre14"/></p>
+<p class="calibre8"><img src="reapermini.png" alt="オレーシャアイコン" class="calibre14"/></p>
 
         </div>
     
Only in book: gm.png
Only in book_mod: images
Common subdirectories: book_mod\META-INF and book\META-INF
Only in book: oreshalarry2.png
Only in book: reaper.png
Only in book: reapermini.png
diff -u book_mod\stylesheet.css book\stylesheet.css
--- book_mod\stylesheet.css	Sat Oct 03 12:20:54 2020
+++ book\stylesheet.css	Sat Oct 03 11:35:26 2020
@@ -400,7 +400,7 @@
     display: table
     }
 .pcalibre7:before {
-    background-image: url(./images/gm.png);
+    background-image: url(./gm.png);
     background-size: 60px 60px;
     content: "";
     display: inline-block;
@@ -408,7 +408,7 @@
     width: 60px
     }
 .pcalibre8:before {
-    background-image: url(./images/takomini.png);
+    background-image: url(./takomini.png);
     background-size: 60px 60px;
     content: "";
     display: inline-block;
@@ -416,7 +416,7 @@
     width: 60px
     }
 .pcalibre9:before {
-    background-image: url(./images/reapermini.png);
+    background-image: url(./reapermini.png);
     background-size: 60px 60px;
     content: "";
     display: inline-block;
Only in book: tako.png
Only in book: takomini.png
```

## result

- epub do not flat rule.(but FBReaderJ need it)
- ebook-convert handle subdirectory.
- ebook-convert use flatten ablility, currently default enable?.

css
`background-image: url(gm.png);`

html
`<img src="tako.png" alt="知性化タコ 「メルクリウスの盗掘屋」" class="calibre8"/>`

## conclusion

Perhaps honkit (old gitbook) is overworking assets for epub

Constraint

- Current ebook-convert process

## attach

- [book.epub.zip](https://github.com/honkit/honkit/files/5321032/book.epub.zip) generate epub
- [book_mod.zip](https://github.com/honkit/honkit/files/5321033/book_mod.zip) modify files
- [book_mod.epub.zip](https://github.com/honkit/honkit/files/5321034/book_mod.epub.zip) re-generate epub from modify files

**Comment by tsuyoshicho** [comment]
related issue

[gitbook-plugin-uml](https://github.com/vowstar/gitbook-plugin-uml) Add-on, and try EPUB/PDF

result
https://github.com/tsuyoshicho/TRPGEPUBTemplate/releases/tag/v0.0.5
https://github.com/tsuyoshicho/TRPGEPUBTemplate/runs/1237936391?check_suite_focus=true#step:9:48

PDF NG
EPUB OK

**Comment by tsuyoshicho** [comment]
# Report

npx honkit --version
3.6.8

Test repo create and result success.
Use same CSS in EPUB/PDF, image attach success.

see:
https://github.com/tsuyoshicho/honkit-gen-sample/releases/tag/v3.0.0

(PDF generate plugin error occur : publish other issue)
