### ISSUE TITLE
locally installed honkit cannot find plugin

### ISSUE THREAD

**Issue by dogatana** [honkit/honkit#133]
## Summary

I've installed honkit that is stored in local folder.
In this case, honkit build fails because it cannot find additional plugin package.

- HonKit version: 3.6.6

## Step to reproduce

1. download `honkit-master.zip` from GitHub and expand it to a local folder, `honkit-master`
2. `yarn install`
3. `yarn run build`
4. create new folder for book, `plugin-test`
5. `npx book init`
6. `npm install  ../<local honkit folder>/packages/honkit`
7. `npm install gitbook-plugin-hide-published-with`
8. `npx honkit build`  fails.

- Link to code example:

book.json - [book.zip](https://github.com/honkit/honkit/files/5303120/book.zip)

package.json - [package.zip](https://github.com/honkit/honkit/files/5303121/package.zip)

## Expected results

honkit uses package module in the book folder.

## Actual results

```
C:\Git\honkit-project\plugin-test> npx honkit build --log=debug
debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "C:\Git\honkit-project\plugin-test\_book"
ReferenceError: Failed to load HonKit's plugin module: "hide-published-with" is not found.

cwd: C:\Git\honkit-project\plugin-test
baseDir:

    at PluginResolver.resolvePluginPackageName (C:\Git\honkit-project\honkit-master\packages\honkit\lib\plugins\PluginResolver.js:72:19)
    at C:\Git\honkit-project\honkit-master\packages\honkit\lib\plugins\loadForBook.js:27:34
    at C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:3016:46
    at List.__iterate (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:3015:23)
    at seqIterate (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:604:16)
    at IndexedIterable.IndexedSeq.__iterate (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:320:14)
    at IndexedIterable.toArray (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:4258:23)
    at List [as constructor] (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:2065:62)
    at reify (C:\Git\honkit-project\honkit-master\packages\honkit\node_modules\immutable\dist\immutable.js:3570:37)

```

## Workaround

Install plugin package in `honkit-master/packages/honkit`

**Comment by azu** [comment]
https://github.com/honkit/honkit/blob/master/packages/honkit/src/plugins/PluginResolver.ts
https://github.com/gbk/try-resolve/blob/master/index.js
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

HonKit use `require.resolve` logic.
I think this is not a normal use case.

What is the use-case?

also, What is happens if use `node_modules/.bin/honkit` instead of `npx honkit`?

**Comment by dogatana** [comment]
Thank you for your reply.

> What is the use-case?

I start using fontawesome 5 with locally installed honkit based on #132 .
At first I assume #132 caused this, but found out that this happens with released honkit as I posted.

> also, What is happens if use node_modules/.bin/honkit instead of npx honkit?

Unfortunately same error happens.

```
C:\Git\honkit-project\plugin-test                                                             
> node_modules\.bin\honkit.cmd build                                                          
ReferenceError: Failed to load HonKit's plugin module: "hide-published-with" is not found.    
```

**Comment by azu** [comment]
> Probably, we need to define the loading logic for the plugin.
> 
> The plugin should be loaded from
> 
> - current directory(This PR)
> - Honkit installed directory(Current maybe)
> - config directory like ESLint
> - configuration like `--cwd` flag
> - other
> 
> Related works: https://github.com/eslint/eslint/blob/b5c8d7389bb2c5d4eae850b866832d099187818b/docs/user-guide/migrating-to-7.0.0.md#plugin-loading-change
> 
> For example, if loading from the current directory, the global installed `honkit` command looks into the local directory at first.
> Is it ok?

https://github.com/honkit/honkit/pull/134#pullrequestreview-499485159

**Comment by dogatana** [comment]
> Probably, we need to define the loading logic for the plugin.

agree.

> - current directory(This PR)
> - Honkit installed directory(Current maybe)

This make sense to me.
By the way, honkit tries to resolve plugin path from **ONLY** one location, doesn't it?
Is there any reason to use one location?
I hope honkit can handle **BOTH** in this order

- try resolve from current book folder
- if it fail, try to resolve default location, honkit package.

> - config directory like ESLint
> - configuration like --cwd flag

I cannot image the case that these will be used.
it may be useful for test, though.

> For example, if loading from the current directory, the global installed honkit command looks into the local directory at first.
> Is it ok?

It's OK and desired for me.
If we want to replace a plugin, we may be able to do by just installing it in a book folder.

**Comment by dogatana** [comment]
honkti  can find installed plugins as I intended with #134 

- `gitbook-plugin-hide-published-with` that is installed in `new_book`
- `plugin-fontsettigs`  that is cloned from `https://github.com/GitbookIO/plugin-fontsettings`to `C:\Git\honkit-project`

```
C:\Git\honkit-project\new_book
> npx honkit build --log=debug
debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "C:\Git\honkit-project\new_book\_book"
debug: plugin path: C:\Git\honkit-project\new_book\node_modules\gitbook-plugin-hide-published-with\package.json
debug: plugin path: C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-highlight\package.json
debug: plugin path: C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-search\package.json
debug: plugin path: C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-lunr\package.json
debug: plugin path: C:\Git\honkit-project\plugin-fontsettings\package.json
debug: plugin path: C:\Git\honkit-project\honkit\packages\honkit\node_modules\@honkit\honkit-plugin-theme-default\package.json
info: 6 plugins are installed
info: 6 explicitly listed
info: plugin "hide-published-with is loaded
info: plugin "highlight is loaded
info: plugin "search is loaded
info: plugin "lunr is loaded
info: plugin "fontsettings is loaded
info: plugin "theme-default is loaded
info: found 1 pages
info: found 6 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme C:\Git\honkit-project\honkit\packages\honkit\node_modules\@honkit\honkit-plugin-theme-default\_assets\website
debug: copy resources from plugin C:\Git\honkit-project\plugin-fontsettings\assets
debug: copy resources from plugin C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-lunr\assets
debug: copy resources from plugin C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-search\assets
debug: copy resources from plugin C:\Git\honkit-project\honkit\packages\honkit\node_modules\gitbook-plugin-highlight\css
debug: copy resources from plugin C:\Git\honkit-project\new_book\node_modules\gitbook-plugin-hide-published-with\book
debug: copy asset ".book.json.un~"
debug: copy asset "book.json~"
debug: copy asset "log1.txt"
debug: copy asset "log2.txt"
debug: copy asset "package-lock.json"
debug: copy asset "package.json"
debug: calling hook "finish:before"
debug: calling hook "finish"
debug: write search index
info: >> generation finished with success in 0.4s !
```

**Comment by dogatana** [comment]
close this too.
