### ISSUE TITLE
CI(publish): calibre installing is failed

### ISSUE THREAD

**Issue by azu** [honkit/honkit#154]
```

2020-11-10 15:36:34 URL:https://download.calibre-ebook.com/linux-installer.sh [31921/31921] -> "-" [1]
Using python executable: /usr/bin/python3
Installing to /opt/calibre
Downloading tarball signature securely...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 800, in script_launch
  File "<string>", line 756, in main
  File "<string>", line 699, in run_installer
  File "<string>", line 669, in download_and_extract
  File "<string>", line 653, in get_tarball_info
  File "<string>", line 629, in get_https_resource_securely
__main__.HTTPError: https://code.calibre-ebook.com/signatures/calibre-3.48.0-x86_64.txz.sha512 returned an unsupported http response code: 404 (Not Found)
The command '/bin/sh -c wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin version=3.48.0' returned a non-zero code: 1
```

https://github.com/honkit/honkit/runs/1380540354?check_suite_focus=true

**Comment by dogatana** [comment]
3.4.8 is too old to download from `https://code.calibre-ebook.com/signatures/`.
At present it's in `https://code.calibre-ebook.com/signatures/old`.

I have no idea how linux-install.sh works.

If included python script gets no arguments, it uses 5.4.0 that is parsed from a raw data downloaded from `https://code.calibre-ebook.com/tarball-info/x86_64`.

This is just a guess, but you specify 3.48.0 explicitly through CI build process?

**Comment by azu** [comment]
Thanks.

It looks that `version` arguments is removed recently.

> 
> Manual binary install
> 
> If you wish to revert to an earlier calibre release or download a calibre upgrade manually, download the tarball of that release from here (choose the 32-bit or 64-bit version, as appropriate). Assuming you want calibre in /opt/calibre, run the following command, changing the path to calibre-tarball.txz below as appropriate: 
>     sudo mkdir -p /opt/calibre && sudo rm -rf /opt/calibre/* && sudo tar xvf /path/to/downloaded/calibre-tarball.txz -C /opt/calibre && sudo /opt/calibre/calibre_postinstall

We need to switch manual binary install.
