### ISSUE TITLE
publish new release to eliminate `npm audit` and GitHub security warnings about dependency urijs

### ISSUE THREAD

**Issue by Trott** [honkit/honkit#184]
## Summary

In a project where this is used, both the GitHub interface and `npm audit` report warnings about `urijs`@1.18.x. This has been addressed in the repo in 161f76b2fff1f0fec7ee428d88657a8bfacce6e3 but that hasn't made it's way into a release yet.

- HonKit version: honkit@3.6.16

## Step to reproduce

1. `npm install honkit && npm audit`

- Link to code example:
n/a

## Expected results

No audit warnings.

## Actual results

```
# npm audit report

urijs  <=1.19.3
Severity: moderate
Hostname spoofing via backslashes in URL - https://npmjs.com/advisories/1595
No fix available
node_modules/urijs
  honkit  *
  Depends on vulnerable versions of urijs
  node_modules/honkit

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

**Comment by azu** [comment]
Thanks for the report!

We have [changed the unnecessary pinned version to `^`](https://github.com/honkit/honkit/pull/185) and released [v3.6.17](https://github.com/honkit/honkit/releases/tag/v3.6.17).
