### ISSUE TITLE
Uncaught TypeError when click a page

### ISSUE THREAD

**Issue by dogatana** [honkit/honkit#191]
## Summary

When I click a page, Console shows the following error.
This does not happen anywhere but in certain places.
(This seems to happen when I click any points within div.page-inner)

```
theme.js:2 Uncaught TypeError: ((ke.event.special[i.origType] || {}).handle || i.handler).apply is not a function
    at HTMLDivElement.dispatch (theme.js:2)
    at HTMLDivElement.v.handle (theme.js:2)
dispatch @ theme.js:2
v.handle @ theme.js:2 
```
![image](https://user-images.githubusercontent.com/12756480/110263871-5389f100-7ffb-11eb-9856-8f39d6730e78.png)

- HonKit version: 3.6.17

## Step to reproduce

1. npx honkit init
2. npx honkit build
3. npx honkit serve
4. click a point on the browser page

- Link to code example:

## Expected results

This error should not happen.

## Actual results

The book seems to work fine, but may affect other scripts.

I'm trying to use Colrobox with a book, but it does not work well so far.
It's just speculation, but I'm guessing that this is a factor.

**Comment by dogatana** [comment]
As a workaround, I added type-check.
But I could not find how this theme.js is derived from ~honkit/packages/@honkit/theme-default/src/js/**/*.js.
Any clue?

```js
                dispatch: function (e) {
                    var t, n, r, o, i, a, s = new Array(arguments.length),
                        u = ke.event.fix(e),
                        l = (Be.get(this, "events") || Object.create(null))[u.type] || [],
                        c = ke.event.special[u.type] || {};
                    for (s[0] = u, t = 1; t < arguments.length; t++) s[t] = arguments[t];
                    if (u.delegateTarget = this, !c.preDispatch || c.preDispatch.call(this, u) !== !1) {
                        for (a = ke.event.handlers.call(this, u, l), t = 0;
                            (o = a[t++]) && !u.isPropagationStopped();)
                            // for (u.currentTarget = o.elem, n = 0;
                            //     (i = o.handlers[n++]) && !u.isImmediatePropagationStopped();) u.rnamespace && i.namespace !== !1 && !u.rnamespace.test(i.namespace) || (u.handleObj = i, u.data = i.data, r = ((ke.event.special[i.origType] || {}).handle || i.handler).apply(o.elem, s), void 0 !== r && (u.result = r) === !1 && (u.preventDefault(), u.stopPropagation()));
                            for (u.currentTarget = o.elem, n = 0; (i = o.handlers[n++]) && !u.isImmediatePropagationStopped();) {
                                if (u.rnamespace && i.namespace !== !1 && !u.rnamespace.test(i.namespace)) {
                                    continue;
                                }
                                u.handleObj = i;
                                u.data = i.data;
                                const tempFunc = (ke.event.special[i.origType] || {}).handle || i.handler;
                                if (typeof tempFunc == "function") {
                                    r = tempFunc.apply(o.elem, s);
                                } else {
                                    console.log("not function!!");
                                }
                                void 0 !== r && (u.result = r) === !1 && (u.preventDefault(), u.stopPropagation());
                            }
```

![image](https://user-images.githubusercontent.com/12756480/110285749-0e7bb400-8027-11eb-91ff-4157c6c1988f.png)

**Comment by azu** [comment]
I've confirmed on https://honkit.netlify.app/

env

- Firefox 86.0
- Chrome 88.0.4324.192

**Comment by dogatana** [comment]
This code itself is a part of jquery.
The latest jquery@3.6.0 has the same code fragment, so this issue happens too with 3.6.0.

But I'm not sure the cause is on the jquery side or the theme-default/**/*.js side.

**Comment by dogatana** [comment]
The following change causes this issue.
Could you confirm and fix it if possible?

https://github.com/honkit/honkit/commit/4fb9cd361d0ae3b40394b632050d77f248ca051d#diff-1d37fa2a682f8eb76b2c020f7403660ed21df2fb6c7739e653ee840f366844f3

![image](https://user-images.githubusercontent.com/12756480/110579036-4d397780-81a9-11eb-98fa-9c32a24b70bd.png)

**Comment by dogatana** [comment]
The method signature seems to say that `focus` accepts false or handler although this is not exactly the same as API document
https://api.jquery.com/focus/

```
(method) JQuery<HTMLElement>.focus(handler?: false | JQuery<TElement = HTMLElement>.TypeEventHandler<HTMLElement, null, HTMLElement, HTMLElement, "focus">): JQuery<...> (+1 overload)
```
Anyway, `{ preventScroll: true }` is not false or a handler.


The following change can fix this issue and seems to fix the scrolling issue.
![image](https://user-images.githubusercontent.com/12756480/111089351-cb619980-856e-11eb-9dce-1b2562e77305.png)

**Comment by azu** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus
We need to use native `focus` instead of jquery `focus`.
jQuery does not support `preventScroll`?

**Comment by dogatana** [comment]
> We need to use native focus instead of jquery focus.
> jQuery does not support preventScroll?

I'm not familiar with native focus and jquery focus.
But the API document has the following three signetures.
```
.focus(handler)
.focus([eventData], handler)
.focus()
```
If we call `.focus({ preventScroll: true })`, this `{ preventScroll: true}` object  is used as the reciever of apply() and it raises exception.
