### ISSUE TITLE
Unnecessary message on console when changing page

### ISSUE THREAD

**Issue by dogatana** [honkit/honkit#202]
## Summary

A message, "page has changed", is displayed every time page is displayed.

- HonKit version: 3.6.19

## Step to reproduce

1. npx honkit init
2. npx honkit build
3. npx honkti serve
4. see console output with browser's developper's tool

## Expected results

These messages should not be displayed.

## Actual results

![image](https://user-images.githubusercontent.com/12756480/112776534-e5c16a00-907a-11eb-8d40-41908713276a.png)

## Proposal

The following function displays this message, so just remove it.
 
- packages/@honkit/theme-default/src/js/core/page.js

```js
function hasChanged(ctx) {
    console.log("page has changed", ctx); // eslint-disable-line no-console
    setState(ctx);

    if (!started) {
        // Notify that gitbook is ready
        started = true;
        events.trigger("start", ctx.config.pluginsConfig);
    }

    events.trigger("page.change");
}
```

**Comment by azu** [comment]
I do not have an opinion on this.
However, I agree to delete `console.log` by default
