### ISSUE TITLE
Possible to add skip-front-matter attribute for asciidoc?

### ISSUE THREAD

**Issue by boydkelly** [honkit/honkit#207]
I have a yaml header in my asciidoc which causes an error with honkit.

I was trying to add the -a skip-front-matter for the asciidoctor command here:
````
function asciidocToHTML(content) {
 return asciidoctor.convert(content, { safe: "server", attributes: { skip-front-matter: true, showtitle: "", icons: "font@" } });
}
````
But honkit is not liking the dash in the attribute:

````
npx honkit build .
node_modules/@honkit/asciidoc/lib/toHTML.js:10
    return asciidoctor.convert(content, { safe: "server", attributes: { skip-front-matter: true, showtitle: "", icons: "font@" } });
                                                                            ^

SyntaxError: Unexpected token '-'
````
Is there a better way?   Thanks!

**Comment by azu** [comment]
>     return asciidoctor.convert(content, { safe: "server", attributes: { skip-front-matter: true, showtitle: "", icons: "font@" } });

This is a syntax error of JavaScript.
JavaScript disallows to use `-` in variable names without quotes.
You need to wrap the property name with a quote.

```diff
-    return asciidoctor.convert(content, { safe: "server", attributes: { skip-front-matter: true, showtitle: "", icons: "font@" } });
+    return asciidoctor.convert(content, { safe: "server", attributes: { "skip-front-matter": true, showtitle: "", icons: "font@" } });
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors

If we want to support customization of the asciidoctor options, we need to add new options in `book.json` like https://github.com/honkit/honkit/issues/107
Welcome to create an issue and PR.
