### ISSUE TITLE
Live-reload does not work in multi language projects.

### ISSUE THREAD

**Issue by i10416** [honkit/honkit#212]
## Summary

Live-reload does not work at all in multi language project probably because  the `Output` finally returned from  `processOutput` in  `generateBook.js` does not have pages of langBook(s), which  prevents `output.reloadPage` from invoking `parsePageFromString`.

I think `processOutput` has too much responsibility. Why don't you separete this into smaller functions?

- HonKit version: ^3.6.20

## Step to reproduce

https://github.com/ItoYo16u/document_template

clone and run `docker-compose up`.

## Expected results
On update, updated file should be generated under outdir.
## Actual results
Logs say `generation finished with success in Ns !` on update, but no file is generated and thus live-reload does not work.

**Comment by azu** [comment]
>  Why don't you separete this into smaller functions?

I agree with you.
Original GitBook has complex code. We want to refactor it and reduce dependencies #40
We have introduces TypeScript for refactoring #24, but this typing is uncompletable.
Welcome to submit Pull Request ❤️

**Comment by azu** [comment]
I've fixed this issue and release https://github.com/honkit/honkit/releases/tag/v3.6.22

Please try it!
