### ISSUE TITLE
The language of the block has spaces

### ISSUE THREAD

**Issue by mouse9527** [honkit/honkit#218]
## Summary

- HonKit version: 3.6.20

## Step to reproduce

1.The language of the block has spaces. eg: ```http request
![image](https://user-images.githubusercontent.com/34568564/131114087-f93faadc-0c45-445b-aebe-de574c4f74c4.png)

**Comment by azu** [comment]
You need to use `http` language by two reasons.

Current markdown parser does not support the lang which has spaces. we need to recreate markdown plugin #96 
HonKit use [highlight.js](https://highlightjs.org/). [highlight.js](https://highlightjs.org/) does support `http` lang, but it does not support `http-request` lang.

    ```http
    POST /task?id=1 HTTP/1.1
    Host: example.org
    Content-Type: application/json; charset=utf-8
    Content-Length: 137

    {
      "status": "ok",
      "extended": true,
      "results": [
        {"value": 0, "type": "int64"},
        {"value": 1.0e+3, "type": "decimal"}
      ]
    }
    ```


<img width="879" alt="image" src="https://user-images.githubusercontent.com/19714/131241317-4a2e0fdd-178b-4b77-b929-79df6d7d6644.png">

**Comment by mouse9527** [comment]
Thanks, i know what i need to do
