### ISSUE TITLE
Feature request: support typical source code files along with markdown files

### ISSUE THREAD

**Issue by laoshaw** [honkit/honkit#239]
Often times I have source code(*.py, *.cpp, *.js) etc mixed with markdown files in the same directory.

Is it possible for honkit to display them and syntax-highlight them the way markdown is handled, use highlight.js for example.

technically I can rename for example my.js to my.js.md and surround the code with   ` ```js ``` ` to achieve similar goal, but it's error prone and tedious.

Thanks for your consideration.

**Comment by azu** [comment]
I've used [gitbook-plugin-include-codeblock](https://github.com/azu/gitbook-plugin-include-codeblock).
This plugin import a file and hightlit it.
