### ISSUE TITLE
URL Masking Not Working

### ISSUE THREAD

**Issue by PhantomNimbi** [honkit/honkit#244]
## Summary
Can't get URL Masking to work with honkit gitbook

- HonKit version: 3.6.23

## Step to reproduce

1. Build and upload a server
2. Set the baseURL in the sitemap plugin

- Link to code example: https://github.com/DevCorner-Github/docs

## Expected results

Should mask the Host IP and internal paths in the address bar

## Actual results

Displays Host IP and internal paths in the address bar

**Comment by azu** [comment]
Can you provide actual file? 
Which file has real IP and full path?

I've ran `npm run build` but I can not found the full path in `_book` dir.

**Comment by PhantomNimbi** [comment]
> Can you provide actual file? Which file has real IP and full path?
> 
> I've ran `npm run build` but I can not found the full path in `_book` dir.

Yo so basically it displays the ip and fullpaht in the address bar instead of the domain. We are trying to make it diplsay the domain via the sitemap plug.

**Comment by PhantomNimbi** [comment]
Never mind, I managed to fix the problem by uploading my site through github pages instead of running it off of my private VPS.

I'm going to go ahead and close this issue now.
