### ISSUE TITLE
Use `URL` instead of urijs

### ISSUE THREAD

**Issue by azu** [honkit/honkit#256]
Node.js has [URL](https://nodejs.org/api/url.html#class-url).
We can use [URL](https://nodejs.org/api/url.html#class-url) instead of urljs.
https://github.com/honkit/honkit/blob/4a439e5aff23b0722b93ab30186f2a30872a12e4/packages/honkit/src/utils/git.ts#L115-L133

## TODO

- [ ] Maybe, Add a test
- [ ] Use `URL` instead of urijs
- [ ] Remove urljs

📝 https://github.com/honkit/honkit/blob/4a08d021e17abc484f3ec3499bda75592d66ac54/packages/honkit/src/templating/conrefsLoader.ts#L8-L17 support git+

**Comment by santhosh-chinnasamy** [comment]
@azu shall I take it up ?

**Comment by azu** [comment]
Yes! Welcome to PR!

**Comment by santhosh-chinnasamy** [comment]
@azu thanks for assigning, I have a query. what is the use of `uri.fragment()` in line `116` ?

**Comment by santhosh-chinnasamy** [comment]
Hi @azu node `URL` is not compatible with ssh urls
Ref: [https://github.com/nodejs/node/issues/36172](https://github.com/nodejs/node/issues/36172)

I think we have to continue with existing implementation. what do you think ?

**Comment by azu** [comment]
@santhosh-chinnasamy Thanks to investigate!

> I think we have to continue with existing implementation. what do you think ?

Ah, You're right.
I want to reduce dependencies, but it looks like better that preserve existing implemention.

Thanks!
