### ISSUE TITLE
reload infinitely when use soft link of node_modules for local serve

### ISSUE THREAD

**Issue by crifan** [honkit/honkit#269]
## Summary

local debug:

`npx honkit serve`

* using normal `node_modules`: OK
* using soft link `node_modules`: infinite reload
   * soft link `node_modules` created by
       * `ln -s ../../generated/honkit/node_modules node_modules`

- HonKit version: `8.5.2`
- node version: `v17.7.1`
- npm version: `8.5.2`

## Step to reproduce

1. npm install honkit --save-dev
2. npx honkit init
3. move `node_modules` to other (common) folder: `../../generated/honkit/node_modules`
4. create ln(soft link) for `node_modules`: `ln -s ../../generated/honkit/node_modules node_modules`
5. npx honkit serve
6. change content -> trigger reload, but infinite reload, reload dead forever

- Link to code example:

## Expected results

**NO** infinite reload == no reload deadlock

## Actual results

infinite reload == reload deadlock

<img width="1398" alt="WX20220611-093903@2x" src="https://user-images.githubusercontent.com/2750682/173167806-2d3eec05-77fc-43e8-ac45-ce87ff11e3c5.png">

**Comment by azu** [comment]
https://github.com/honkit/honkit/blob/4a439e5aff23b0722b93ab30186f2a30872a12e4/packages/honkit/src/cli/watch.ts#L23-L27
Probably, We can avoid infinity loop by adding `node_modules` to `ignored` pattern.
However, I don't understand if it resolve all symlink issue.

**Comment by crifan** [comment]
Thanks for your reply.

Final worked by add `node_modules` to `ignored` list:

* `honkit/lib/cli/watch.js`

```js
    const watcher = chokidar_1.default.watch(toWatch, {
        cwd: dir,
        // ignored: "_book/**",
        ignored: ["_book/**", "node_modules/**"],
        ignoreInitial: true,
    });
```

<img width="1011" alt="honkit watcher ignore" src="https://user-images.githubusercontent.com/2750682/176344898-d7848c77-69f0-441e-a5f8-c04ab8cb5a08.png">

-> so
* here: `ignored` work for `ln -s` symlink
  * If not work, others may try `followSymlinks` for `chokidar`'s `watcher`
