### ISSUE TITLE
Fontawesome seems broken in v4.0.2

### ISSUE THREAD

**Issue by deepakprabhakara** [honkit/honkit#303]
## Summary

- HonKit version: 4.0.2

## Step to reproduce

1. Run honkit locally with an example
2. Load localhost:4000 in a browser
3. Font icons are missing since foontawesome is not found

- Link to code example: Any example will do. Seems broken on https://honkit.netlify.app/ as well

## Expected results

Font icons should show correctly

## Actual results

Font icons are broken

**Comment by azu** [comment]
May be related with #301 
cc @deviantintegral

**Comment by azu** [comment]
Fixed in [v4.0.3](https://github.com/honkit/honkit/releases/tag/v4.0.3).

Thanks for report!

**Comment by deviantintegral** [comment]
Excellent! This was my next item to look into. _Of course_ it was the same issue. This fix led to our tests passing at https://github.com/Lullabot/information-security-policy/pull/125.
