### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by azu** [honkit/honkit#32]
We need to provide docker image.

Would be nice like that

```
$ docker run --rm -it honkit/honkit honkit build
$ docker run --rm -it honkit/honkit honkit serve
$ docker run --rm -it honkit/honkit honkit pdf # need ebook-convert 
```

📝 Need to publish from CI like https://github.com/secretlint/secretlint/blob/master/.github/workflows/publish-artifact.yml
Dependency order: publish npm → push Docker Image

## UseCase

- Non-Node.js user easy to use HonKit
- Use Docker Image instead of installing `ebook-convert` into globally

**Comment by azu** [comment]
https://github.com/secretlint/secretlint/tree/master/publish/docker
secretlint has similar approch

**Comment by azu** [comment]
How to load custom plugin?

**Comment by HugoDF** [comment]
> How to load custom plugin?

At that point could we assume that users should be building their own Docker image using the honkit one as base?

**Comment by azu** [comment]
Yes, It is actual solution.

Probably, Docker user need to extend the base image for loading custom plugins.

**Comment by HugoDF** [comment]
Couple other questions to clarify are

- which Docker repository should we be using? DockerHub? GitHub?
- automatic publishing/tagging of the Docker image? I'm guessing there should be a GitHub Action for that?

**Comment by azu** [comment]
> which Docker repository should we be using? DockerHub? GitHub?

DockerHub.

> automatic publishing/tagging of the Docker image? I'm guessing there should be a GitHub Action for that?

Yes. It require CI setting like 

- https://github.com/secretlint/secretlint/blob/master/.github/workflows/publish.yml git tag and create github release, and trigger `publish-artifact`
- https://github.com/secretlint/secretlint/blob/master/.github/workflows/publish-artifact.yml `publish-artifact` does npm publish and docker push

This would require also auto publishing npm package workbecause Docker image require latest npm package.
npm publish → docker push.

Currently, I've published new package from my local env.
We need to move this workflow to GitHub Actions.

**Comment by azu** [comment]
📝 I've added main UseCase to Issue description.

**Comment by Amrithnath** [comment]
Hey, is this taken? I would like to work on this as well,

**Comment by HugoDF** [comment]
@Amrithnath go for it, let us know if you need any help

**Comment by Amrithnath** [comment]
cool will do

**Comment by azu** [comment]
I've added basic dockerfile and create new release flow( https://github.com/honkit/honkit/issues/32#issuecomment-650728304 )

```
docker run -v `pwd`:`pwd` -w `pwd` --rm -it honkit/honkit honkit --help
Usage: honkit [options] [command]

Options:
  -V, --version                    output the version number
  -h, --help                       display help for command

Commands:
  build [options] [book] [output]  build a book
  serve [options] [book] [output]  serve the book as a website for testing
  parse [options] [book]           parse and print debug information about a book
  init [options] [book]            setup and create files for chapters
  pdf [options] [book] [output]    build a book into an ebook file
  epub [options] [book] [output]   build a book into an ebook file
  mobi [options] [book] [output]   build a book into an ebook file
  help [command]                   display help for command
```

https://github.com/honkit/honkit/tree/master/docker
https://github.com/honkit/honkit/blob/master/CONTRIBUTING.md#release-flow

We need to improve this `Dockerfile`. Welcome to contribute 👍

**Comment by azu** [comment]
GitHub release Public registry.
https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by azu** [comment]
I've added `ebook-convert` into Dockerfile  #125

We need to provide way that copy custom font into docker contaienr.

**Comment by HugoDF** [comment]
> I've added `ebook-convert` into Dockerfile  #125
> 
> We need to provide way that copy custom font into docker contaienr.

Would a volume mount work for allowing custom fonts to be available from inside the container?

Also noticed that Docker isn't documented as an installation option, I'll send over a PR later.

**Comment by azu** [comment]
> Would a volume mount work for allowing custom fonts to be available from inside the container?

Not yet.
I've just extended the docker image for custom fonts.
https://github.com/azu/JavaScript-Plugin-Architecture/blob/master/Dockerfile
But, I bet there's a better way.

> Also noticed that Docker isn't documented as an installation option, I'll send over a PR later.

Nice!

**Comment by HugoDF** [comment]
> > Would a volume mount work for allowing custom fonts to be available from inside the container?
> 
> Not yet.
> I've just extended the docker image for custom fonts.
> https://github.com/azu/JavaScript-Plugin-Architecture/blob/master/Dockerfile
> But, I bet there's a better way.

Oh you meant using the fonts as per the machine's environment
