### ISSUE TITLE
code blocks not getting syntax highlighted 

### ISSUE THREAD

**Issue by nablidev** [honkit/honkit#354]
## md code block doesn't highlight any syntax

- HonKit version: "^4.0.7"

## package.json
```json

{
"devDependencies": {
    "honkit": "^4.0.7"
  },
  "dependencies": {
    "@honkit/honkit-plugin-highlight": "^4.0.8",
    "ebook-convert": "^2.0.1",
    "gitbook-plugin-chapter-fold": "^0.0.4",
    "gitbook-plugin-hide-published-with": "^0.0.1",
    "gitbook-plugin-hints": "^1.0.2",
    "gitbook-plugin-mermaid-newface": "^4.1.0",
    "gitbook-plugin-theme-creative": "^1.0.6"
  }
}

```

## book.json

```json
{
"plugins": [
    "chapter-fold",
    "hide-published-with",
    "hints",
    "mermaid-newface",
    "theme-creative"
  ],
}
```

## code example in an md file
````markdown

```javascript
person.toString = function () {
  return "I'm " + this.age;
};
```

````

## Expected results

highlighted code in the served web page or generated pdf

## Actual results

no highlighted code in the served web page or generated pdf

![image](https://github.com/honkit/honkit/assets/33099326/492f3e08-3e06-4fa4-bb6a-66fb33acdd68)

### Edit:

So the corresponding code block in md is converted like the following in the browser:

![image](https://github.com/honkit/honkit/assets/33099326/62bc727f-e598-4029-9704-0c9531d3792a)

So for some reason, the **highlight.js** library doesn't work. And after some investigation, I can't see it anywhere loaded in the browser neither as a library nor as a plugin.

**Comment by azu** [comment]
Thanks for repot.
Reproducing repository helps us to debug.

- https://github.com/azu/honkit-issue-354

I removed `mermaid-newface` from book.json, syntax highlight works again.

<img width="878" alt="image" src="https://github.com/honkit/honkit/assets/19714/07cfd704-79aa-4a2e-818c-246430120bab">

Probably, `mermaid-newface` cause this issue.
You can open a new issue to `mermaid-newface`.

It is not HonKit's core issue, I'm closing this issue.

**Comment by nablidev** [comment]
@azu Thank you for finding the reason why the code block didn't render properly. I was doubting that one of the plugins is causing the issue but didn't continue on that path of reasoning about it. However, that was something obvious that I overlooked since the `mermaid-newface` alters the behavior of the code block and indeed it was the reason behind causing that the code blocks didn't render correctly. So how I am going to do about it now is that first I am going to omit the use of the `mermaid-newface` plugin then I am going to simply include the `mermaid diagrams` as simple `images` in my `honkit` project. Unfortunately there is no single `gitbook/honkit` mermaid plugin available that is able to render relatively new `mermaid` syntax and diagrams. All of them are outdated and the only plugin that was able to do the job was `mermaid-newface` but it is causing the code blocks to behave wrongly. As I said I am going to stick to using simple images for the diagrams until there is a good solution for rendering `mermaid diagrams` in `honkit/gitbook`.
