### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tez3998** [honkit/honkit#377]
First of all, thank you for creating a great tool and providing these documents.

I opened this issue to report a broken link in [the chapter titled "Context and APIs"](https://honkit.netlify.app/plugins/api) in the document.  The link labeled as "book.js" appears to be broken.

Could you please fix the link?

**Comment by azu** [comment]
Probably, `book.js` point to https://github.com/honkit/honkit/blob/master/packages/honkit/src/models/book.ts.
I think the link was broken when I rewrote GitBook to HonKit(TypeScript).
