### ISSUE TITLE
default-theme: Drop jQuery

### ISSUE THREAD

**Issue by azu** [honkit/honkit#39]
We can drop jQuery.
Because, support browser is modern browser.

**Comment by azu** [comment]
Maybe, It will break plugins...

**Comment by HugoDF** [comment]
How would you feel about leveraging something like Alpine.js? 7kb gzipped and would probably cover the majority of the use cases:

- binding to arrow keys
- dropdowns
- toggling sidebars

Would also mean we can drop the whole "js" directory (with Alpine I think we could write most of the toggling logic right in the HTML markup)

**Comment by azu** [comment]
Alpine.js is good.
We aim to less dependency and light weight file size, and get maintanceable.

Probably, React or Vue is too rich for HonKit's theme.
[Docusaurus](https://docusaurus.io/), [VuePress](https://vuepress.vuejs.org/), and [@nuxt/content](https://content.nuxtjs.org/)  is suitable for rich web book.

We might want to create new (default?) theme instead of drop jQuery from default theme, because I do not how many GitBook plugins depened on jQuery. #57 

https://github.com/honkit/honkit/blob/025344d16113594e62864986d11e044cb9b8fec8/packages/%40honkit/theme-default/src/js/core/index.js#L34-L37

Theme is a plugin. so we can replace default theme with another theme.

Move this issue to #57

**Comment by HugoDF** [comment]
Makes sense, worth closing this issue maybe?

**Comment by azu** [comment]
Ok. close this issue. → Move to #57
