### ISSUE TITLE
can not render line break

### ISSUE THREAD

**Issue by rfhits** [honkit/honkit#420]
## Summary

I can not write something multiline.
In markdown, I can write "hello world" in two lines like this:

```markdown
hello<whitespace><whitespace>
world
```
GitHub renders it like below:

---

hello  
world

---

"hello world" will appear on two lines, but in honkit it will be rendered in three lines.

- HonKit version: 5.1.4

## Step to reproduce

1. init a book
2. write something need to be in the same paragraph but in multilines
3. honkit serve

I need to write some lyrics in the markdown, so they should in the same paragraph.

![image](https://github.com/user-attachments/assets/f723b075-3663-4a8e-ace5-f9780e6af36f)

**Comment by rfhits** [comment]
it seems that honkit renders two <br>

**Comment by davmillar** [comment]
Confirmed by adding the following test in `packages/@honkit/markdown/src/__tests__/page.ts`:

```ts
    it("should handle line breaks appropriately", () => {
        assert.equal(page("Line one.  \nLine two.").content, "<p>Line one.<br>Line two.</p>");
    });
```

I'm just getting familiarized with this repo so I don't have a fix yet, but you may be able to simply insert a `<br>` tag after "hello" manually if your use case allows.
