### ISSUE TITLE
Support Node 22, Drop Node 16

### ISSUE THREAD

**Issue by davmillar** [honkit/honkit#430]
## Summary

Drop support for Node 16 and add support for Node 22.

_HonKit version: 5.1.4 (to 6.x)_

Many of the dependencies for HonKit have updated versions, but many of them have dropped Node 16 support now that it reached end of life. I think it would make sense to release a new major version with dropped Node 16 support and added Node 22 support and update some of the dependencies in the process.

@azu  if you are okay with this, I would be willing to start the work and consult with you when I think I've reached dev-completion.

**Comment by azu** [comment]
Yes.

When we are done merging the current patch/minor PRs, it would be good to update them with major updates.
