### ISSUE TITLE
Uncertain use of Git name trademark

### ISSUE THREAD

**Issue by ojn** [honkit/honkit#48]
It seems that Git committee doesn't approve of the use as part of the name in projects not affiliated with them.

There is a lengthy discussion on mailing list here
https://public-inbox.org/git/20170202022655.2jwvudhvo4hmueaw@sigill.intra.peff.net/

and their written guidelines
https://www.git-scm.com/about/trademark

Maybe something with "Book" word could be a better name?

**Comment by azu** [comment]
Thanks for notice!
We need to consider to other name.

**Comment by azu** [comment]
https://twitter.com/azu_re/status/1274693495320539138
I've generate random words.
![image](https://user-images.githubusercontent.com/19714/85225855-fd463500-b40e-11ea-8066-749f56c22ae5.png)

`Kit` is popular word.

**Comment by azu** [comment]
Variaout "hon" postfix pattern

```
makehon
mkhon
jithon
gethon
gohon
ehon
rakhon
athon
tighon
anohon
```

https://twitter.com/ysaito8015/status/1274700368069484547

**Comment by azu** [comment]
HonKit looks like good, but It seem like HomeKit(apple).

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/85227546-25d32c80-b419-11ea-96bf-ce7a1cb5fe1e.png)

Rough sketch for imagination.

**Comment by azu** [comment]
We have decided to rename GitHon to HonKIt! 

Create new issue for migration.

- [Rename GitHon to HonKit · Issue #52 · githon/githon](https://github.com/githon/githon/issues/52)

**Comment by azu** [comment]
We have renamed `GitHon` to `HonKit` 🎉 

@ojn Thanks again 👍
