### ISSUE TITLE
Bibliography?

### ISSUE THREAD

**Issue by atrent** [honkit/honkit#61]
Hi, I have searched for the term "bibliography" in the docs with no avail.
Does honkit support some kind of bibliography?
Similar to LaTeX I mean, the environment I use nowadays, I have tons of .bib files...
Thank you

**Comment by azu** [comment]
It seems that Original GitBook(Legacy) did not support bibliography.
https://github.com/GitbookIO/gitbook/search?q=bibliography&unscoped_q=bibliography
Is this feature request?

HonKit support GitBook plugins.
These plugina may be available. 

- [NeoTim/gitbook-plugin-bibtex-citations-and-references](https://github.com/NeoTim/gitbook-plugin-bibtex-citations-and-references)
- [manuelmitasch/gitbook-plugin-bibtex-citation](https://github.com/manuelmitasch/gitbook-plugin-bibtex-citation)

**Comment by atrent** [comment]
No RFE, just a question to see if this tool might be a substitute for what I'm using now, LaTeX, that has disadvantages of course, above all in generating ebooks, but it's a winner for everything else.
The answer is: "no, honkit cannot replace LaTeX" (and probably it wasn't designed to be a replacement).
Thank you!

**Comment by azu** [comment]
>  The answer is: "no, honkit cannot replace LaTeX" (and probably it wasn't designed to be a replacement).

Yes. HonKit will not be LaTeX alternative.

[My book](https://github.com/asciidwango/js-primer)(japanese) use HonKit for web site and publication use LaTeX.
The LaTeX is generated from Markdown by [pandoc](https://pandoc.org/) and fix manually.

You may be interested in [Re:VIEW](https://github.com/kmuto/review).
