### ISSUE TITLE
Rename to HonKit in code base

### ISSUE THREAD

**Issue by azu** [honkit/honkit#63]
We should use "HonKit" name in our code base.
Some code and docs still use original name.

https://github.com/honkit/honkit/blob/ef556874f42d27a4d7b323acbc92fcadd579d034/packages/honkit/src/output/ebook/getConvertOptions.js#L29-L30

:memo: Note

`honkit` variables does not implemented yet #36

**Comment by HugoDF** [comment]
I'm happy to do this one
