### ISSUE TITLE
TypeScript: target is es2018

### ISSUE THREAD

**Issue by azu** [honkit/honkit#66]
HonKit support Node.js LTS - Node.js 10+.

- https://github.com/nodejs/Release 

So, we need to change `tsconfig.json`'s target to `es2018` or `es2017`.
(Node.js 10 does not suppor ES2019)
https://github.com/honkit/honkit/blob/b9267fcd5888e8c25750413f7a36a43a4481c5be/tsconfig.json#L3

https://node.green/#ES2017
https://node.green/#ES2018

It is part of TypeScript migration #24 .

📝 Currently, HonKit code does not use ES2019 features and it is not problem.
Also, TypeScript only transpile syntax.

**Comment by azu** [comment]
`"target": "node10",` is best, but tsconfig.json does not support [browserslist-syntax](https://github.com/browserslist/browserslist).

**Comment by harshilparmar** [comment]
@azu Can I try this issue?

**Comment by azu** [comment]
@harshilparmar YES! Welcome to PR!

**Comment by harshilparmar** [comment]
@azu  Sorry to ask but there is only one change right !! If I am wrong please guide me.

**Comment by HugoDF** [comment]
@harshilparmar yeah it should be in the tsconfig

**Comment by harshilparmar** [comment]
Ok I am going to make pr for that 😁

**Comment by azu** [comment]
This is fixed in #71
