### ISSUE TITLE
Failed to load HonKit's plugin module: "mathjax" is not found.

### ISSUE THREAD

**Issue by fanninpm** [honkit/honkit#72]
## Summary

Failed to load HonKit's plugin module: "mathjax" is not found.

- HonKit version:

```
$ honkit --version
error: unknown option '--version'
```

## Steps to reproduce

1. Make a fresh book with `honkit init`
2. Add `book.json` and `package.json` to source directory as below
3. Keep running `yarn install` to no avail

- Link to code example:

<details>
<summary>book.json</summary>

```json
{
    "plugins" : [
        "fontsettings",
        "mathjax@https://github.com/algorithm-archivists/plugin-mathjax",
        "bibtex-cite",
        "wordcount",
        "api-language-selector@https://github.com/algorithm-archivists/gitbook-plugin-api-language-selector.git",
        "include-codeblock",
        "ga",
        "bulk-redirect",
        "prism",
        "-highlight"
    ]
}
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "honkit-demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "gitbook-plugin-mathjax": "https://github.com/algorithm-archivists/plugin-mathjax",
    "honkit": "^3.4.1"
  }
}
```
</details>

## Expected results

`gitbook-plugin-mathjax` loads without fault.

## Actual results

```
$ honkit build --log=debug
debug: readme found at README.md 
debug: summary file found at SUMMARY.md 
debug: cleanup folder "/Users/padraicfanning/Documents/honkit-demo/_book" 
Failed to load HonKit's plugin module: "mathjax" is not found.

cwd: /Users/padraicfanning/Documents/honkit-demo
baseDir: 



```

**Comment by azu** [comment]
Thanks for report.

Maybe #68 is related.

It seems that failed to `require("gitbook-plugin-mathjax")` in project dir.

```
    "gitbook-plugin-mathjax": "https://github.com/algorithm-archivists/plugin-mathjax",
```

Git dependencies may be related. We'll look into this.

**Comment by azu** [comment]
@fanninpm I've createed reproduce repository.
https://github.com/azu/honkit-issue-72
But, It can not reporoduce.

Could you install dependencies via `yarn install`?

HonKit does not support `gitbook install`.
Instead of it, you can just use `yarn install` or `npm install`.

**Comment by fanninpm** [comment]
My `package.json` did not have

```json
"scripts": {
    "build": "honkit build",
    "serve": "honkit serve"
  },
```

Including this block and running `yarn run build` or `yarn run serve` fixed the problem. (You may want to update the documentation accordingly.)

**Comment by azu** [comment]
`npx honkit build` and `yarn honkit build`  has same behavior.
In my local env, both run success.

**Comment by azu** [comment]
Probably, Do you have installed `honkit` globally?
global `honkit` and local `honkit` load plugins from different directory.

global `honkit` require to install plugins globally.

**Comment by fanninpm** [comment]
> Global honkit require to install plugins globally.

That's exactly the problem. I have now altered the workflow so that `honkit` and the book's plugins are both local dependencies.

**Comment by azu** [comment]
Thanks to confirm.

I've created a document issue.
https://github.com/honkit/honkit/issues/74
