### ISSUE TITLE
gitbook-plugin-uml not work properly

### ISSUE THREAD

**Issue by elferia** [honkit/honkit#82]
## Summary

gitbook-plugin-uml, a plugin that renders plantuml diagram, does not work properly on HonKit.
This is a problem of not the plugin but HonKit because it works on gitbook-cli.

- HonKit version: 3.5.0

## Step to reproduce

1. `npm init --yes`
1. `npm install honkit --save-dev`
1. `npx honkit init`
1. `npm install gitbook-plugin-uml --save-dev`
1. edit `book.json`
1. edit `README.md`
1. `npx honkit serve`

- Link to code example:

### book.json
```json
{
    "plugins": ["uml"]
}
```

### README.md
````markdown
```uml
@startuml

/'
  Comment
 '/

	Class Stage
	Class Timeout {
		+constructor:function(cfg)
		+timeout:function(ctx)
		+overdue:function(ctx)
		+stage: Stage
	}
 	Stage <|-- Timeout

@enduml
```
````

I guess a plantuml source including special characters like `/` failed to be rendered.

## Expected results

The diagram would be rendered.

## Actual results

An image that says there is an error appears.

```
$ npx honkit build --log=debug
debug: readme found at README.md 
debug: summary file found at SUMMARY.md 
debug: cleanup folder "/home/elferia/honkit-uml/_book" 
info: 6 plugins are installed 
info: 6 explicitly listed 
info: plugin "uml is loaded
info: plugin "highlight is loaded
info: plugin "search is loaded
info: plugin "lunr is loaded
info: plugin "fontsettings is loaded
info: plugin "theme-default is loaded
info: found 1 pages 
info: found 5 asset files 
debug: calling hook "config" 
debug: calling hook "init" 
warn: "book" property is deprecated, use "this" directly instead 
debug: copy assets from theme /home/elferia/honkit-uml/node_modules/@honkit/honkit-plugin-theme-default/_assets/website 
debug: copy resources from plugin /home/elferia/honkit-uml/node_modules/gitbook-plugin-fontsettings/assets 
debug: copy resources from plugin /home/elferia/honkit-uml/node_modules/gitbook-plugin-lunr/assets 
debug: copy resources from plugin /home/elferia/honkit-uml/node_modules/gitbook-plugin-search/assets 
debug: copy resources from plugin /home/elferia/honkit-uml/node_modules/gitbook-plugin-highlight/css 
debug: copy asset "assets/images/uml/65902d3d2519f65a9fe3a4e91401058002521178.svg" 
debug: copy asset "assets/images/uml/67802308346393fc5d1d4a0e1efc555904eb64ba.svg" 
debug: copy asset "assets/images/uml/c3c103d2bede49665226ff9cc9acb9a330da3174.svg" 
debug: copy asset "package-lock.json" 
debug: copy asset "package.json" 
debug: calling hook "finish:before" 
debug: calling hook "finish" 
debug: write search index 
info: >> generation finished with success in 0.4s !
```

**Comment by azu** [comment]
This rendering error is caused by `/` as you expected.


[gitbook-plugin-uml](https://github.com/vowstar/gitbook-plugin-uml) convert 

    ```uml
    @startuml
    
    /'
      Comment
    '/
    
        Class Stage
        Class Timeout {
            +constructor:function(cfg)
            +timeout:function(ctx)
            +overdue:function(ctx)
            +stage: Stage
        }
        Stage <|-- Timeout
    
    @enduml
    ```

to 

    {% uml %}
    @startuml
    
    /'
      Comment
    '/
    
        Class Stage
        Class Timeout {
            +constructor:function(cfg)
            +timeout:function(ctx)
            +overdue:function(ctx)
            +stage: Stage
        }
        Stage <|-- Timeout
    
    @enduml
    {% enduml %}

HonKit's markdown parser try to escape `/` because `/` is not in Indented CodeBlock.

So, plainuml recive `\/` (escaped value) and display rendering error.

**Workaround 1:** add indent to comment. HonKit treat the comment as CodeBlock. It means that does not escape `/`.

    ```uml
    @startuml
    
        /'
          Comment
        '/
    
        Class Stage
        Class Timeout {
            +constructor:function(cfg)
            +timeout:function(ctx)
            +overdue:function(ctx)
            +stage: Stage
        }
        Stage <|-- Timeout
    
    @enduml
    ```

**Workaround 2:**  use another uml plugin like [ansanloms/honkit-plugin-uml](https://github.com/ansanloms/honkit-plugin-uml).

📝 [gitbook-plugin-uml](https://github.com/vowstar/gitbook-plugin-uml) depend on old GitBook parser behavior strongy #58 
I'm thinking that we fix it as a bug.

- Tested repository: https://github.com/azu/honkit-example-gitbook-plugin-uml

**Comment by elferia** [comment]
Hi

Workaround 2 looks better so I tried, but not worked. Diagrams are ignored, even error images are not rendered.
I guess [ansanloms/honkit-plugin-uml](https://github.com/ansanloms/honkit-plugin-uml) does not support syntax like

````
```uml
@startuml
````

as well as [gitbook-plugin-puml-aleung](https://www.npmjs.com/package/gitbook-plugin-puml-aleung), but not tested.

So I tried Workaround 1, then the diagrams rendered successfully.
But other problems occurred. It it not proper to discuss other problems here, but I would like to report.
For example, markdown as below will not be rendered as expected:

````
~~~md
 ```mermaid
 graph TD;
   A-->B;
   A-->C;
   B-->D;
   C-->D;
 ```
~~~
````

I would like to report this as another issue and hope to be fixed, but I cannot afford.
I will try HonKit in the future.
Thank you.

**Comment by azu** [comment]
@elferia Thank for details!

Current HonKit has GitBook(legacy) incomatibility and [CommonMark](https://commonmark.org/) incompatiblity in markdown.
So, I proposed to improve compatiblity with GitBook(legacy) in https://github.com/honkit/honkit/issues/77#issuecomment-653592952

Simply to say: use GitBook v3 markdown parser.

We'll inverstigate it in this weekend.

**Comment by azu** [comment]
We have released https://github.com/honkit/honkit/releases/tag/v3.5.1
It will fix this issue.

Please try it.

```
npm install honkit@3.5.1
# prune cache
npx honkit build --reload
```

**Comment by azu** [comment]
If this is still happend, please reopen it.

**Comment by elferia** [comment]
I tried HonKit 3.5.2 and everything is rendered successfully!
Thank you very much.

**Comment by azu** [comment]
Thanks to confirm! 🎉
