### ISSUE TITLE
Docs: Add an Examples page

### ISSUE THREAD

**Issue by fanninpm** [honkit/honkit#93]
Now that the [Arcane Algorithm Archive](https://www.algorithm-archive.org/) has successfully [migrated from GitBook to HonKit](https://github.com/algorithm-archivists/algorithm-archive/pull/720), I was wondering if there's any interest in including this in the (currently nonexistent) Examples page in the HonKit documentation.

**Comment by azu** [comment]
Thanks to suggestion!

I've add examples page 📜 
Welcome to Pull Request!

https://honkit.netlify.app/examples.html

**Comment by azu** [comment]
closed by #97
