### ISSUE TITLE
markdown checkbox not rendered

### ISSUE THREAD

**Issue by c19** [honkit/honkit#95]
```
- [x] checked
- [ ] todo
```
above markdown should rendered like this:

- [x] checked
- [ ] todo

but we got this: 

![image](https://user-images.githubusercontent.com/2505428/87014812-3fd58300-c1ff-11ea-9b78-7455791dc6d8.png)

**Comment by c19** [comment]
"honkit": "3.5.2" is used. no settings changed.

**Comment by azu** [comment]
Yes. HonKit markdown does not support [GFM tasklist extension](https://github.github.com/gfm/).
Original GitBook(Legacy) also does not support this.

So, you need to use some plguins.

- [ly-tools/gitbook-plugin-todo: A plugin to embed readonly todo list in your Gitbook](https://github.com/ly-tools/gitbook-plugin-todo)
- [yhor1e/honkit-plugin-todo](https://github.com/yhor1e/honkit-plugin-todo)

📝 We will try to rewrite HonKit markdown parser for getting more CommonMark and GFM.

[New markdown parser · Issue #96 · honkit/honkit](https://github.com/honkit/honkit/issues/96)
