### ISSUE TITLE
Full Typesetting and Rendering Control

### ISSUE THREAD

**Issue by sirinath** [honkit/honkit#99]
Can finer control over typesetting be enabled using shortcodes or other means so we can create documents and books which render well on the web as well as print? E.g. https://latex.js.org/ can render documents similar to LaTeX.

**Comment by azu** [comment]
Maybe it related to https://github.com/honkit/honkit/issues/61

> HonKit will not be LaTeX alternative.
> https://github.com/honkit/honkit/issues/61#issuecomment-650519399

HonKit main target is a web and it uses Markdown.
Its purpose is far with Full Typesetting.
